name: Deploy to shinyapps.io

on:
  push:
    branches: [ "main" ]   # cambia se deployi da un altro branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'   # non deve per forza coincidere con shinyapps.io

      # Non è obbligatorio ripristinare tutto con renv per il deploy;
      # rsconnect basta. Lascia commentato il blocco sotto se vuoi velocità.
      # - name: Restore packages with renv
      #   uses: r-lib/actions/setup-renv@v2

      - name: Install rsconnect
        run: Rscript -e 'install.packages("rsconnect")'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          APP_DIR:          ${{ secrets.APP_DIR }}   # vuoto = "."
        run: |
          Rscript -e 'rsconnect::setAccountInfo(
                        name   = Sys.getenv("SHINYAPPS_NAME"),
                        token  = Sys.getenv("SHINYAPPS_TOKEN"),
                        secret = Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e '
            appDir  <- Sys.getenv("APP_DIR"); if (!nzchar(appDir)) appDir <- ".";
            appName <- basename(normalizePath(appDir));
            rsconnect::deployApp(appDir = appDir,
                                 appName = appName,
                                 account = Sys.getenv("SHINYAPPS_NAME"))'
